language: go

services:
  - docker

go:
  - 1.9

before_install:
  - sudo apt-get update
  - sudo apt-get install unzip curl
  - curl https://releases.hashicorp.com/nomad/0.7.0/nomad_0.7.0_linux_amd64.zip -o nomad.zip
  - curl https://releases.hashicorp.com/consul/1.0.0/consul_1.0.0_linux_amd64.zip -o consul.zip
  - sudo unzip -o -d  /usr/local/bin ./nomad.zip
  - sudo unzip -o -d  /usr/local/bin ./consul.zip
  - sudo chmod +x /usr/local/bin/consul
  - sudo chmod +x /usr/local/bin/nomad
  - git clone -b additions https://github.com/nicholasjackson/certify-incubator.git $GOPATH/src/github.com/openfaas/certify-incubator
  - cd $GOPATH/src/github.com/openfaas/certify-incubator && git checkout additions

script:
  - echo "Build and Test"
  - make test
  - make build_docker
  - echo "Run Functional Tests"
  - source ./startNomad.sh
  - cat ./consul.hcl
  - cat ./nomad.hcl
  - nomad run nomad_job_files/faas.hcl
  - sleep 10
  - nomad status faas-nomadd
  - docker ps
  - cd $GOPATH/src/github.com/openfaas/certify-incubator && gateway_url=$FAAS_GATEWAY go test ./tests -v
  - nomad status
  - cat $HOME/log/nomad.log
  - cat $HOME/log/consul.log
  - ps -aux | grep nomad
  - ps -aux | grep consul
